"""
Multi-Asset Scenario Analysis Demo

Uses the pretrained JumpHMM portfolio model (424 S&P 500 tickers) with
Student-t copula dependence to:
1. Simulate correlated multi-asset paths
2. Compute cross-asset market mood
3. Price American options on a target ticker
4. Compare calm vs stressed scenario pricing

Pretrained model: generated by the training script in
    https://github.com/varnerlab/eCornell-AI-finance-lectures.git
    → code/scripts/train-portfolio-surrogate.jl
Place the output JLD2 file at: data/pretrained-portfolio-surrogate.jld2
"""

using JumpHMM
using HestonIV
using JLD2
using StatsBase: ordinalrank
using Statistics
using Random
using LinearAlgebra

# --- Step 1: Load pretrained portfolio model ---
const PRETRAINED_PATH = joinpath(@__DIR__, "..", "data", "pretrained-portfolio-surrogate.jld2")

if isfile(PRETRAINED_PATH)
    println("Loading pretrained portfolio model...")
    portfolio_data = JLD2.load(PRETRAINED_PATH)
    tickers_all = portfolio_data["tickers"]
    marginals = portfolio_data["marginals"]
    copula = portfolio_data["copula"]
    println("  → $(length(tickers_all)) tickers, copula type: $(typeof(copula))")

    # Select a subset of tickers for the demo
    SELECTED = ["AAPL", "MSFT", "GOOGL", "AMZN", "META"]
    selected_tickers = filter(t -> t in keys(marginals), SELECTED)

    # Reconstruct a PortfolioModel from the pretrained components
    ticker_to_col = Dict(t => i for (i, t) in enumerate(tickers_all))
    portfolio = PortfolioModel(
        selected_tickers,
        Dict(t => marginals[t] for t in selected_tickers),
        copula,
        Dict(t => ticker_to_col[t] for t in selected_tickers),
        ""
    )
    TARGET = "AAPL"
    S0 = 200.0
else
    println("Pretrained model not found. Building a demo portfolio on synthetic data...")
    println("  (For full S&P 500 model, run train-portfolio-surrogate.jl from")
    println("   https://github.com/varnerlab/eCornell-AI-finance-lectures.git)")

    Random.seed!(42)
    n_days = 1000
    n_assets = 3
    selected_tickers = ["TICK_A", "TICK_B", "TICK_C"]

    Σ_returns = [1.0 0.7 0.5; 0.7 1.0 0.6; 0.5 0.6 1.0]
    L = cholesky(Σ_returns).L
    P0s = [150.0, 300.0, 130.0]
    prices_matrix = Matrix{Float64}(undef, n_days + 1, n_assets)
    prices_matrix[1, :] .= P0s
    for t in 1:n_days
        z = L * randn(n_assets)
        for j in 1:n_assets
            prices_matrix[t+1, j] = prices_matrix[t, j] * exp(0.0003 + 0.015 * z[j])
        end
    end

    portfolio = fit(PortfolioModel, selected_tickers, prices_matrix;
                    dependence=StudentTCopula, N=50, rf=0.05)
    portfolio = tune(portfolio, prices_matrix; n_paths=200)
    TARGET = selected_tickers[1]
    S0 = prices_matrix[end, 1]
end

println("  → Selected tickers: $(join(selected_tickers, ", "))")
println("  → Target: $TARGET, Spot: \$$(round(S0, digits=2))")

# --- Step 2: Set up Heston parameters ---
heston_params = HestonParameters(4.0, 0.35)  # κ, σ_v (v₀ derived from θ per contract)

N_states = portfolio.marginals[TARGET].partition.N
N_tail = portfolio.marginals[TARGET].jump.N_tail

θ_states = fill(0.04, N_states)
for s in 1:N_tail
    θ_states[s] = 0.10
end
for s in (N_states - N_tail + 1):N_states
    θ_states[s] = 0.0625
end

θ_func = ThetaHybrid(
    θ_states,
    [0.20, -0.20, -0.02, 0.5],  # DTE decay, skew, interaction, smile curvature
    0.8                     # higher mood sensitivity (multi-asset mood is informative)
)

# --- Step 3: Define contracts on target ticker ---
contracts = [
    OptionContract(round(S0 * 0.95), 30, :put, :american),   # 5% OTM put
    OptionContract(round(S0),        30, :call, :american),   # ATM call
    OptionContract(round(S0 * 1.05), 30, :call, :american),   # 5% OTM call
    OptionContract(round(S0 * 0.90), 7,  :put, :american),    # 10% OTM weekly put
]

# --- Step 4: Run multi-asset scenario ---
println("\nRunning multi-asset scenario (500 paths × 252 steps)...")
result = run_scenario(
    portfolio, heston_params, θ_func, contracts,
    TARGET, S0;
    n_sim_steps=252, n_paths=500,
    eval_step=5, r_f=0.05, seed=456
)

# --- Step 5: Analyze ---
println("\n" * "="^60)
println("MULTI-ASSET SCENARIO RESULTS — $TARGET")
println("  Cross-asset mood from: $(join(selected_tickers, ", "))")
println("="^60)

stats = summarize(result)
println("\nPaths: $(stats[:n_paths])")
println("Mean IV: $(round(stats[:iv_mean]*100, digits=2))%")
println("Mean mood (cross-asset): $(round(stats[:mood_mean], digits=3))")
println("Max mood: $(round(stats[:mood_max], digits=3))")

println("\n--- Option Prices ---")
for cs in stats[:contracts]
    c = cs[:contract]
    type_str = c.option_type == :call ? "CALL" : "PUT "
    println("  $(type_str) K=$(c.K) DTE=$(c.DTE): " *
            "mean=\$$(round(cs[:mean_price], digits=2)) " *
            "std=\$$(round(cs[:std_price], digits=2)) " *
            "[$(round(cs[:q05], digits=2)), $(round(cs[:q95], digits=2))]")
end

# --- Step 6: Compare tail vs non-tail scenarios ---
println("\n--- Tail Event Analysis ---")
final_mood = result.mood_paths[:, 1]
stressed = final_mood .> 0.0
calm = .!stressed

if sum(stressed) > 0 && sum(calm) > 0
    println("  Calm paths: $(sum(calm)), Stressed paths: $(sum(stressed))")
    for (i, c) in enumerate(contracts)
        type_str = c.option_type == :call ? "CALL" : "PUT "
        mean_calm = mean(result.option_prices[calm, i])
        mean_stress = mean(result.option_prices[stressed, i])
        println("  $(type_str) K=$(c.K) DTE=$(c.DTE): " *
                "calm=\$$(round(mean_calm, digits=2)) " *
                "stress=\$$(round(mean_stress, digits=2)) " *
                "ratio=$(round(mean_stress/max(mean_calm, 0.01), digits=2))x")
    end
else
    println("  (insufficient tail events for comparison)")
end
