"""
Single-Ticker Scenario Analysis Demo

Uses a pretrained JumpHMM portfolio model (424 S&P 500 tickers) to:
1. Load pretrained marginal model for a chosen ticker
2. Simulate synthetic price paths
3. Run Heston variance process → IV → CRR American option pricing
4. Analyze option price distributions

Pretrained model: generated by the training script in
    https://github.com/varnerlab/eCornell-AI-finance-lectures.git
    → code/scripts/train-portfolio-surrogate.jl
Place the output JLD2 file at: data/pretrained-portfolio-surrogate.jld2
"""

using JumpHMM
using HestonIV
using JLD2
using Statistics
using Random

# --- Step 1: Load pretrained model (or train a small fallback) ---
const PRETRAINED_PATH = joinpath(@__DIR__, "..", "data", "pretrained-portfolio-surrogate.jld2")

if isfile(PRETRAINED_PATH)
    println("Loading pretrained portfolio model...")
    portfolio_data = JLD2.load(PRETRAINED_PATH)
    marginals = portfolio_data["marginals"]
    TICKER = "AAPL"
    model = marginals[TICKER]
    S0 = 200.0  # approximate current AAPL price
    println("  → $(length(portfolio_data["tickers"])) tickers available")
else
    println("Pretrained model not found. Training a demo model on synthetic data...")
    println("  (For full S&P 500 model, run train-portfolio-surrogate.jl from")
    println("   https://github.com/varnerlab/eCornell-AI-finance-lectures.git)")

    Random.seed!(42)
    n_days = 1000
    S0 = 100.0
    prices = Vector{Float64}(undef, n_days + 1)
    prices[1] = S0
    for i in 1:n_days
        prices[i+1] = prices[i] * exp(0.0003 + 0.015 * randn())
    end
    S0 = prices[end]

    model = fit(JumpHiddenMarkovModel, prices; N=50, rf=0.05)
    model = tune(model, prices; n_paths=200)
    TICKER = "DEMO"
end

println("  → $TICKER model: N=$(model.partition.N), ϵ=$(round(model.jump.ϵ, digits=4)), λ=$(round(model.jump.λ, digits=1))")
println("  → Spot price: \$$(round(S0, digits=2))")

# --- Step 2: Set up Heston parameters ---
heston_params = HestonParameters(
    5.0,    # κ: mean-reversion speed
    0.3     # σ_v: vol-of-vol
)
# Note: v₀ is computed automatically per contract as θ(s₀, DTE, K/S₀, M₀)
# so each strike/DTE gets its own initial IV — smile and term structure emerge naturally

# ThetaHybrid: one θ per HMM state + ψ adjustment + mood sensitivity
N_states = model.partition.N
θ_states = fill(0.04, N_states)  # baseline θ ≈ 20% IV for all states

# Make tail states have higher θ (higher baseline vol in stress)
N_tail = model.jump.N_tail
for s in 1:N_tail
    θ_states[s] = 0.09        # ~30% IV for bottom tail (bearish)
end
for s in (N_states - N_tail + 1):N_states
    θ_states[s] = 0.0625      # ~25% IV for top tail (bullish, less extreme)
end

θ_func = ThetaHybrid(
    θ_states,
    [0.20, -0.15, -0.01, 0.5],  # β: DTE decay, skew, interaction, smile curvature
    0.5                     # γ: 50% mood sensitivity
)

# --- Step 3: Define option contracts (relative to current price) ---
contracts = [
    OptionContract(round(S0 * 0.95), 30, :put, :american),   # 5% OTM put
    OptionContract(round(S0),        30, :call, :american),   # ATM call
    OptionContract(round(S0 * 1.05), 30, :call, :american),   # 5% OTM call
    OptionContract(round(S0),        60, :put, :american),    # ATM 60 DTE put
]

# --- Step 4: Run scenario ---
println("\nRunning scenario (1000 paths × 252 steps)...")
result = run_single_asset_scenario(
    model, heston_params, θ_func, contracts, S0;
    n_sim_steps=252, n_paths=1000, eval_step=5,
    r_f=0.05, seed=123
)

# --- Step 5: Analyze results ---
println("\n" * "="^60)
println("SCENARIO RESULTS — $TICKER")
println("="^60)

stats = summarize(result)
println("\nPaths: $(stats[:n_paths]), Steps: $(stats[:n_steps])")
println("Mean IV (final step): $(round(stats[:iv_mean]*100, digits=2))%")
println("IV Std: $(round(stats[:iv_std]*100, digits=2))%")
println("Mean mood: $(round(stats[:mood_mean], digits=3))")

println("\n--- Option Price Distributions ---")
for cs in stats[:contracts]
    c = cs[:contract]
    type_str = c.option_type == :call ? "CALL" : "PUT "
    println("  $(type_str) K=$(c.K) DTE=$(c.DTE):")
    println("    Mean: \$$(round(cs[:mean_price], digits=2))")
    println("    Std:  \$$(round(cs[:std_price], digits=2))")
    println("    5%-95% CI: [\$$(round(cs[:q05], digits=2)), \$$(round(cs[:q95], digits=2))]")
end

# --- Step 6: Examine variance paths ---
println("\n--- Variance Process Diagnostics ---")
v_means = mean(result.variance_paths, dims=1)[1, :]
v_min = minimum(result.variance_paths)
v_max = maximum(result.variance_paths)
println("  Variance range: [$(round(v_min, digits=6)), $(round(v_max, digits=4))]")
println("  Mean variance (t=1): $(round(v_means[1], digits=4))")
println("  Mean variance (t=end): $(round(v_means[end], digits=4))")
println("  Fraction of paths with v > 0.16 (>40% IV): $(round(mean(result.variance_paths[:, end] .> 0.16), digits=3))")
